#define AUTO_INITIALIZE_EASYLOGGINGPP
//#define ELPP_NO_DEFAULT_LOG_FILE
#define ELPP_DEFAULT_LOG_FILE "TestReplayLogger.log"
#define ELPP_UNICODE
#define ELPP_THREAD_SAFE
#define ELPP_FORCE_USE_STD_THREAD
#define ELPP_DISABLE_DEFAULT_CRASH_HANDLING
#define ELPP_STL_LOGGING
